backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"

    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: heroImage, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: CTA Title, name: ctaTitle, widget: string }
          - { label: CTA Path, name: ctaPath, widget: string }
          - {
              label: Why Businesses Choose Contourna?,
              name: services,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: CTA Title, name: ctaTitle, widget: string },
                  { label: CTA Path, name: ctaPath, widget: string },
                  {
                    label: Services Stat Cards,
                    name: service-stat-cards,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: text },
                        { label: Content, name: content, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Contourna Solutions,
              name: solutions,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Solutions Cards,
                    name: home-solution-cards,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: text },
                        { label: Content, name: content, widget: text },
                        { label: CTA Title, name: ctaTitle, widget: string },
                        { label: CTA Path, name: ctaPath, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: How It Works,
              name: how-it-works,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: How it works list,
                    name: how-it-works-list,
                    widget: list,
                    fields:
                      [
                        { label: List Heading, name: listHeading, widget: text },
                        { label: List Content, name: listContent, widget: text },
                      ],
                  },
                  { label: copy, name: copy, widget: string },
                  { label: CTA Title, name: ctaTitle, widget: string },
                  { label: CTA Path, name: ctaPath, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/company/index.md"
        label: "Company"
        name: "company"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "company-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/quote/index.md"
        label: Get a free quote
        name: "quote"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "quote-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/services/index.md"
        label: Services
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/solutions/index.md"
        label: Solutions
        name: "solutions"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    
